### ISSUE TITLE
Document which types use locks internally

### ISSUE THREAD

**Issue by stevenengler** [al8n/atomic-time#1]
I think it would be helpful to document which types use locking rather than atomic primitives. For example `atomic_time::AtomicDuration` uses locking, which you can see with this compile-time check:

```rust
const _: () = {
  // this assertion fails since `PodDuration` is 12 bytes with an alignment of 4 bytes
  assert!(Atomic::<PodDuration>::is_lock_free());
};
```

**Comment by al8n** [comment]
Hi, good point! I will add a feature `lockfree` which will guarantee all of the implementations are played around with `u64`, but when users enable this feature, they are aware they will lose the nanosecond information.

**Comment by stevenengler** [comment]
It might be worth considering going the other way instead. If you were to store only the nanoseconds as a u64 with a max of 2^64 nanoseconds, that covers 584 years which is probably long enough for most use cases. That might make the API tricky though since converting from a `std::time::Duration` could then fail.

But either way doesn't matter to me, I just thought I'd leave a comment while I was passing by. I don't have a current use case for this lib, but I've wanted an atomic duration in the past so I'll keep this library in mind if I need one again in the future.

**Comment by al8n** [comment]
Closed this issue, solved by the latest commit. `core::sync::atomic::AtomicU128` was used when enabling `nightly` feature, `portable-atomic::AtomicU128` was used in stable.
